security:
  oauth2:
    client:
      scope: password
      client-id: todo-list-api
      client-secret: 123

spring:

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_todo
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update

  flyway:
    enable: true
    baseline-on-migrate: on
    schemas: db_todo
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/db_todo
    locations: classpath:db/migration

logging:
  level:
    root: info

server:
  port: 8080